services:
  - type: web
    name: satpam-ga-engine
    env: python
    plan: free
    buildCommand: pip install -r ga_engine/requirements.txt
    startCommand: uvicorn ga_engine.api.app:app --host 0.0.0.0 --port 8000
    autoDeploy: true
